/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visão;

import Controle.ConectaBanco;
import Controle.ControleParcelamentoVenda;
import Modelo.ModeloTabela;
import Modelo.ModeloParcelamentoVenda;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Eduardo
 */
public class FrmParcelamento extends javax.swing.JFrame {
        int qtdParcela=0,i=1, cont =1;
        float porc,valorVenda=0,valorParcela=0;  // variaveis globais 
        float valorAtuParc=0,valorTotal=0;;
        
         ConectaBanco conex = new ConectaBanco();
          ModeloParcelamentoVenda mod = new ModeloParcelamentoVenda();
          ControleParcelamentoVenda control = new ControleParcelamentoVenda();
    /**
     * Creates new form FrmParcelamento
     */
    public FrmParcelamento(int cod) {// para chamar o codigo através do método fechar venda
        initComponents();
       
       
        conex.conexao();       
        
        conex.execultasql("select * from venda where id_venda = "+cod);// vai na tabela venda e compara o codigo com o parametro cod
       
        try {
            conex.rs.first();         // busca o cod , valor da venda e a data da venda e coloca nesses campos 
            jTextFieldCodgVenda.setText(String.valueOf(cod));
            jTextFieldValorVenda.setText(String.valueOf(conex.rs.getFloat("valor_venda")));
            jTextFieldData.setText(String.valueOf(conex.rs.getString("data_venda")));
           
            
                    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao buscar a venda!\n Erro"+ ex);
        }
        
    }

    private FrmParcelamento() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodgVenda = new javax.swing.JTextField();
        jTextFieldValorVenda = new javax.swing.JTextField();
        jTextFieldData = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldQuantParcelas = new javax.swing.JTextField();
        jTextFieldJuroParcelas = new javax.swing.JTextField();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jButtonParcelar = new javax.swing.JButton();
        jButtonGerarDuplicatas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Parcelamento de Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Codigo Venda:");

        jLabel3.setText("Valor da Venda:");

        jLabel4.setText("Data:");

        jLabel5.setText("Quantidade de Parcelas:");

        jLabel6.setText("Juros das Parcelas:");

        jLabel7.setText("Valor Total:");

        jButtonParcelar.setText("Parcelar");
        jButtonParcelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParcelarActionPerformed(evt);
            }
        });

        jButtonGerarDuplicatas.setText("Gerar Duplicatas");
        jButtonGerarDuplicatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarDuplicatasActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldCodgVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldQuantParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonParcelar)
                                        .addGap(32, 32, 32)
                                        .addComponent(jButtonGerarDuplicatas)))))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel3)
                                .addGap(173, 173, 173)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldJuroParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jTextFieldValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel6)
                                .addGap(124, 124, 124)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodgVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJuroParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonParcelar)
                    .addComponent(jButtonGerarDuplicatas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonParcelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParcelarActionPerformed
        // TODO add your handling code here:
        // faz o cauculo das parcelas
        
          String[] options = {"Sim", "Não"};

        int resposta = JOptionPane.showOptionDialog(null, "Tem certeza que deseja parcelar agora ?",
                "Confirmar",JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        

        if (resposta == 1) {
        	
        	return;//Este é o Botao do NAO. Ira retornar para a Calculadora
        }
        
        
       
        
        if(resposta == 0){//Este é o Botao do SIM. Ira sair do seu Programa
        
        qtdParcela = Integer.parseInt(jTextFieldQuantParcelas.getText());// Tem que converter por ela vira de um campo como uma string
        porc = Float.parseFloat(jTextFieldJuroParcelas.getText());        
        valorVenda = Float.parseFloat(jTextFieldValorVenda.getText());        
        valorParcela = valorVenda/qtdParcela;
        tabela.removeAll();
        }
        preecherTabela();
        
        
    }//GEN-LAST:event_jButtonParcelarActionPerformed

    private void jButtonGerarDuplicatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarDuplicatasActionPerformed
        // TODO add your handling code here:
        
        int j=1;
        String datavenc = jTextFieldData.getText();
        String dia,mes,ano;
        //dia= 
                
       dia = ""+datavenc.charAt(0)+datavenc.charAt(1)+"/";
       mes = ""+datavenc.charAt(3)+datavenc.charAt(4);
       ano = "/"+datavenc.charAt(6)+datavenc.charAt(7)+datavenc.charAt(8)+datavenc.charAt(9);// mes dia e ano   
       int anoInt = Integer.parseInt("" + datavenc.charAt(6)+datavenc.charAt(7)+datavenc.charAt(8)+datavenc.charAt(9));// converte o ano para inteiro
       int mesInt = Integer.parseInt(mes);// converte o mes para inteiro
       
       while(j< cont){
           
           if(mesInt < 10){
           
           mod.setCodVenda(Integer.parseInt(jTextFieldCodgVenda.getText()));
           mod.setValorParcela(valorParcela + (valorParcela * (porc / 100 )));
           mod.setValor_total(Float.parseFloat(jTextFieldValorTotal.getText()));
           mod.setValor_venda(Float.parseFloat(jTextFieldValorVenda.getText()) );
           mod.setNumeroParc(j);
           mod.setDataVenc(dia + "0" + mesInt + "/"+ anoInt);
           
           control.SalvaParcela(mod);
           
           
       }else{
            
               
           mod.setCodVenda(Integer.parseInt(jTextFieldCodgVenda.getText()));
           mod.setValorParcela(valorParcela + (valorParcela * (porc / 100 )));
           mod.setValor_total(Float.parseFloat(jTextFieldValorTotal.getText()));
           mod.setValor_venda(Float.parseFloat(jTextFieldValorVenda.getText()) );
           mod.setNumeroParc(j);
           mod.setDataVenc(dia + "" + mesInt + "/"+ anoInt);
           
           control.SalvaParcela(mod);
           
               
               
         }
           
           mesInt++;
           if(mesInt > 12){
               
               anoInt++;
               mesInt = 1;
               
           }
           
          j++; 
           
       }
       
        JOptionPane.showMessageDialog(rootPane, "Parcelas geradas");
        
         dispose();
        
    }//GEN-LAST:event_jButtonGerarDuplicatasActionPerformed

      public void preecherTabela(){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Código","Data","Valor"};
        
      // float valorAtuParcela=0,valorTotal=0;
       
       String data = jTextFieldData.getText();
       String dia, mes, ano; // Variaveis para armazenar data
       
       dia = ""+data.charAt(0)+data.charAt(1)+"/";
       mes = ""+data.charAt(3)+data.charAt(4);
       ano = "/"+data.charAt(6)+data.charAt(7)+data.charAt(8)+data.charAt(9);// mes dia e ano   
      valorAtuParc = valorParcela + (valorParcela * (porc/100)); // formula para calculo de porcentagem
       
       int anoInt = Integer.parseInt("" + data.charAt(6)+data.charAt(7)+data.charAt(8)+data.charAt(9));// converte o ano para inteiro
       int mesInt = Integer.parseInt(mes);// converte o mes para inteiro
       
        while(i<=qtdParcela){
            
             valorTotal = valorTotal + valorAtuParc;// valor total da venda parcelada
             
             if(mesInt > 9 ){
           
               // dados.add(new Object[]{i,dia+(Integer.parseInt(mes)+i)+ano,valorAtuParcela});
             
                  dados.add(new Object[]{i,dia + mesInt + "/" + anoInt,valorAtuParc});
             }else{
                 
                
                  
                   dados.add(new Object[]{i,dia + "0" + mesInt + "/" + anoInt,valorAtuParc});//  ex 15/06/2015 se for menor que 10 concaquena zero
          
             }
             
             mesInt++;// o mes e icrementado ex: 2,3,4,5...
             
             if(mesInt  > 12 ){// se o mes for maior que 12 
                 
                 anoInt++;// incrementa o ano novo valor para ano
                 mesInt = 1;// E o mes retorna ao mes 1 inicia o ano novamente
             }
            
             
             i ++;
             cont ++;// gera o numero de parcelas
          }
          
      jTextFieldValorTotal.setText(String.valueOf(valorTotal));// escreve no formulario o valor total da venda e preenche a tabela
              
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
            tabela.setModel(modelo);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(100);
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(2).setPreferredWidth(230);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getTableHeader().setReorderingAllowed(false);
            tabela.setAutoResizeMode(tabela.AUTO_RESIZE_OFF);
            tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                         
                              
          
      
            
            

}        
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmParcelamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmParcelamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmParcelamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmParcelamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmParcelamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerarDuplicatas;
    private javax.swing.JButton jButtonParcelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCodgVenda;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldJuroParcelas;
    private javax.swing.JTextField jTextFieldQuantParcelas;
    private javax.swing.JTextField jTextFieldValorTotal;
    private javax.swing.JTextField jTextFieldValorVenda;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
