/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visão;

import Controle.ConectaBanco;
import Controle.ControleBotoesItensVendaProduto;
import Controle.ControleExcluirParcelas;
import Controle.ControleExcluirVendas;
import Modelo.ModeloExcluirVendas;
import Modelo.ModeloTabela;
import Modelo.ModeloVenda;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Eduardo
 */
public class FrmTabelaDeVendasParceladas extends javax.swing.JFrame {
    
DecimalFormat formato;// Variavel global para DecimalFormat
    ConectaBanco conn = new ConectaBanco();
     float total=0; // variavel global para icrementar total do dia
    //ControleExcluirVendas ctl = new ControleExcluirVendas();
     
    ControleBotoesItensVendaProduto ctl = new ControleBotoesItensVendaProduto();
    
    ControleExcluirParcelas ctlp = new ControleExcluirParcelas();
    ModeloVenda m = new ModeloVenda();
    ModeloExcluirVendas mv = new ModeloExcluirVendas();
    ModeloExcluirVendas mvv = new ModeloExcluirVendas();
     int rep=0;
    
     
     public FrmTabelaDeVendasParceladas() {
         
        initComponents();
        
        this.setExtendedState(this.getExtendedState() | Principal.MAXIMIZED_BOTH);// para maximizar a tela
         
         
        formato = new DecimalFormat("#0.00"); // Cria um campo para pegar dois numeros apos o ponto.
        conn.conexao();
        preecherTabela("select * from parcela_venda");
        preecherTabela2("select * from itens_venda_produto");
        preecherTabela3("select sum(valor_venda)as valor_venda from venda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButtonPrimeiro1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonUltimo1 = new javax.swing.JButton();
        jButtonDeletar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonDeletar2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelcv = new javax.swing.JLabel();
        jLabeldt = new javax.swing.JLabel();
        jLabelvl = new javax.swing.JLabel();
        jLabelcli = new javax.swing.JLabel();
        jLabeltp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2Valor = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        jLabelParcela = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelCodVenda = new javax.swing.JLabel();
        jLabelValorTotal = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelValorVenda = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelValorParcela = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabelNumeroParcela = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabelDataVencimento = new javax.swing.JLabel();
        jButtonPesquisarCodV = new javax.swing.JButton();
        jTextFieldPesqCodV = new javax.swing.JTextField();
        jButtonCod = new javax.swing.JButton();
        jTextFieldCod = new javax.swing.JTextField();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle de vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 3));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Clique sobre as parcelas pagas !");

        jButtonPrimeiro1.setText("<<");
        jButtonPrimeiro1.setToolTipText("Primeiro");
        jButtonPrimeiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiro1ActionPerformed(evt);
            }
        });

        jButton5.setText("<");
        jButton5.setToolTipText("Anterior");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText(">");
        jButton6.setToolTipText("Próximo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButtonUltimo1.setText(">>");
        jButtonUltimo1.setToolTipText("Último");
        jButtonUltimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimo1ActionPerformed(evt);
            }
        });

        jButtonDeletar1.setText("Deletar");
        jButtonDeletar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletar1ActionPerformed(evt);
            }
        });

        jButton1.setText("Deletar Tudo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jButtonPrimeiro1)
                        .addGap(30, 30, 30)
                        .addComponent(jButton5)
                        .addGap(29, 29, 29)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUltimo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeletar1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrimeiro1)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButtonUltimo1)
                    .addComponent(jButtonDeletar1)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Parcelas pagas:");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 3));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.setColumnSelectionAllowed(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Clique sobre as vendas Avista !");

        jButtonPrimeiro.setText("<<");
        jButtonPrimeiro.setToolTipText("Primeiro");
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonUltimo.setText(">>");
        jButtonUltimo.setToolTipText("Último");
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButton2.setText(">");
        jButton2.setToolTipText("Próximo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("<");
        jButton3.setToolTipText("Anterior");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonDeletar.setText("Deletar Tudo");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jButtonDeletar2.setText("Deleta codigo");
        jButtonDeletar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonPrimeiro)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUltimo)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonDeletar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeletar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButtonDeletar)
                    .addComponent(jButtonDeletar2)))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Vendas a vista");

        jDesktopPane1.setBackground(new java.awt.Color(51, 0, 51));

        jLabelcv.setForeground(new java.awt.Color(0, 255, 255));
        jLabelcv.setText("Codigo Venda");

        jLabeldt.setForeground(new java.awt.Color(51, 255, 255));
        jLabeldt.setText("cod");

        jLabelvl.setForeground(new java.awt.Color(0, 255, 255));
        jLabelvl.setText("qtv");

        jLabelcli.setForeground(new java.awt.Color(0, 255, 255));
        jLabelcli.setText("nomeProd");

        jLabeltp.setForeground(new java.awt.Color(0, 255, 255));
        jLabeltp.setText("R$");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Codigo Venda :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CodProd");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Qtv");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NomeProd");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Valor");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("R$");

        jLabel2Valor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2Valor.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2Valor.setText("Valor");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 255));
        jLabel12.setText("Calcular :");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabelcv)
                .addGap(88, 88, 88)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabeldt)
                .addGap(106, 106, 106)
                .addComponent(jLabel8)
                .addGap(44, 44, 44)
                .addComponent(jLabelvl)
                .addGap(114, 114, 114)
                .addComponent(jLabel9)
                .addGap(72, 72, 72)
                .addComponent(jLabelcli, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(38, 38, 38)
                .addComponent(jLabeltp)
                .addGap(221, 221, 221))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(39, 39, 39)
                .addComponent(jLabel2Valor)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcv)
                    .addComponent(jLabeldt)
                    .addComponent(jLabelvl)
                    .addComponent(jLabelcli)
                    .addComponent(jLabeltp)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2Valor)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(jLabelcv, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabeldt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelvl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelcli, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabeltp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2Valor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setText("Atualizar");
        jButton4.setToolTipText("Atualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jDesktopPane2.setBackground(new java.awt.Color(51, 0, 51));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CP:");

        jLabelParcela.setForeground(new java.awt.Color(51, 255, 51));
        jLabelParcela.setText("Parcela");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CV:");

        jLabelCodVenda.setForeground(new java.awt.Color(51, 255, 51));
        jLabelCodVenda.setText("Venda");

        jLabelValorTotal.setForeground(new java.awt.Color(0, 255, 0));
        jLabelValorTotal.setText("total");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("VAL.VD");

        jLabelValorVenda.setForeground(new java.awt.Color(51, 255, 51));
        jLabelValorVenda.setText("Valor");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Valor.T");

        jLabelValorParcela.setForeground(new java.awt.Color(51, 255, 51));
        jLabelValorParcela.setText("Valor");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Numero.P");

        jLabelNumeroParcela.setForeground(new java.awt.Color(51, 255, 51));
        jLabelNumeroParcela.setText("....");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("VALOR.P");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("DATA.VENC:");

        jLabelEstado.setForeground(new java.awt.Color(51, 255, 51));
        jLabelEstado.setText("....");

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("ESTADO:");

        jLabelDataVencimento.setForeground(new java.awt.Color(51, 255, 51));
        jLabelDataVencimento.setText("../../..");

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelParcela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCodVenda)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabelValorVenda)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabelNumeroParcela)
                .addGap(37, 37, 37)
                .addComponent(jLabel22)
                .addGap(34, 34, 34)
                .addComponent(jLabelValorParcela)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(26, 26, 26)
                .addComponent(jLabelDataVencimento)
                .addGap(28, 28, 28)
                .addComponent(jLabel25)
                .addGap(32, 32, 32)
                .addComponent(jLabelEstado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabelParcela)
                    .addComponent(jLabel13)
                    .addComponent(jLabelCodVenda)
                    .addComponent(jLabel16)
                    .addComponent(jLabelValorVenda)
                    .addComponent(jLabel18)
                    .addComponent(jLabelValorTotal)
                    .addComponent(jLabel20)
                    .addComponent(jLabelNumeroParcela)
                    .addComponent(jLabel22)
                    .addComponent(jLabelValorParcela)
                    .addComponent(jLabel23)
                    .addComponent(jLabelDataVencimento)
                    .addComponent(jLabel25)
                    .addComponent(jLabelEstado))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jDesktopPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabelParcela, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabelCodVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabelValorTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabelValorVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabelValorParcela, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabelNumeroParcela, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabelEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabelDataVencimento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonPesquisarCodV.setText("Codigo venda");
        jButtonPesquisarCodV.setToolTipText("Pesquisar codigo de venda");
        jButtonPesquisarCodV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCodVActionPerformed(evt);
            }
        });

        jTextFieldPesqCodV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldPesqCodV.setForeground(new java.awt.Color(0, 51, 51));

        jButtonCod.setText("Codigo venda");
        jButtonCod.setToolTipText("Pesquisar codigo de venda");
        jButtonCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCodActionPerformed(evt);
            }
        });

        jTextFieldCod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCod.setForeground(new java.awt.Color(0, 51, 51));

        jDesktopPane3.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 51));
        jLabel14.setText("Valor Total do produtos vendidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)
                        .addComponent(jTextFieldPesqCodV, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonPesquisarCodV)
                        .addGap(148, 148, 148)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCod)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jDesktopPane2)
            .addComponent(jDesktopPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesqCodV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisarCodV)
                            .addComponent(jLabel1)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCod))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         String id = ""+jTable1.getValueAt(jTable1.getSelectedRow(),0);// preço para o jtxtFieldPreco
          jLabelParcela.setText(id);
          String cod = ""+jTable1.getValueAt(jTable1.getSelectedRow(),1);// preço para o jtxtFieldPreco
          jLabelCodVenda.setText(cod);
          
           String vl = ""+jTable1.getValueAt(jTable1.getSelectedRow(),2);// preço para o jtxtFieldPreco
           jLabelValorVenda.setText(vl);
           
            String vt = ""+jTable1.getValueAt(jTable1.getSelectedRow(),3);// preço para o jtxtFieldPreco
            jLabelValorTotal.setText(vt);
            
             String n = ""+jTable1.getValueAt(jTable1.getSelectedRow(),4);// preço para o jtxtFieldPreco
             
             jLabelNumeroParcela.setText(n);
             
              String vp = ""+jTable1.getValueAt(jTable1.getSelectedRow(),5);// preço para o jtxtFieldPreco
              jLabelValorParcela.setText(vp);
             
              String da = ""+jTable1.getValueAt(jTable1.getSelectedRow(),6);// preço para o jtxtFieldPreco
              jLabelDataVencimento.setText(da);
              
               String est = ""+jTable1.getValueAt(jTable1.getSelectedRow(),7);// preço para o jtxtFieldPreco
               
               jLabelEstado.setText(est);
              
              
        
         float x;
        
       
         String preco = ""+jTable1.getValueAt(jTable1.getSelectedRow(),5);// preço para o jtxtFieldPreco
          
             
             
              x = Float.parseFloat(preco); // conversão do preco para float
              
              
              total=total+x; // variavel global incrementa             
              
             //jTextFieldTotal.setText(String.valueOf(total));
              //jLabel2Valor.setText(String.valueOf(total));
             jLabel2Valor.setText(formato.format(total));//Imprime dois numeros apos o ponto.
             
           
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
         float y;
        
        String cd = ""+jTable2.getValueAt(jTable2.getSelectedRow(),0);// preço para o jtxtFieldPreco
        jLabelcv.setText(cd);
        
         String da = ""+jTable2.getValueAt(jTable2.getSelectedRow(),1);// preço para o jtxtFieldPreco
         jLabeldt.setText(da);
         
         String tp = ""+jTable2.getValueAt(jTable2.getSelectedRow(),2);// preço para o jtxtFieldPreco
         
         jLabelvl.setText(tp);
         
          String cdl = ""+jTable2.getValueAt(jTable2.getSelectedRow(),3);// preço para o jtxtFieldPreco
          jLabelcli.setText(cdl);
           String preco = ""+jTable2.getValueAt(jTable2.getSelectedRow(),4);// preço para o jtxtFieldPreco
          
             jLabeltp.setText(preco);
             
              y = Float.parseFloat(preco); // conversão do preco para float
              
              
              total=total+y; // variavel global incrementa             
              
             //jTextFieldTotal.setText(String.valueOf(total));
             // jLabel2Valor.setText(String.valueOf(total));
             jLabel2Valor.setText(formato.format(total));//Imprime dois numeros apos o ponto.
             
          
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:
        
        m = ctl.Primeiro();
        jLabelcv.setText(String.valueOf(m.getIdVenda()));
        jLabeldt.setText(String.valueOf(m.getIdProduto()));
        jLabelvl.setText(String.valueOf(m.getQtdItem()));
        jLabelcli.setText(String.valueOf(m.getNomeProduto()));
        jLabeltp.setText(String.valueOf(m.getValorVenda()));
        
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        m = ctl.Ultimo();
        jLabelcv.setText(String.valueOf(m.getIdVenda()));
        jLabeldt.setText(String.valueOf(m.getIdProduto()));
        jLabelvl.setText(String.valueOf(m.getQtdItem()));
        jLabelcli.setText(String.valueOf(m.getNomeProduto()));
        jLabeltp.setText(String.valueOf(m.getValorVenda()));
        
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         m = ctl.Proximo();
        jLabelcv.setText(String.valueOf(m.getIdVenda()));
        jLabeldt.setText(String.valueOf(m.getIdProduto()));
        jLabelvl.setText(String.valueOf(m.getQtdItem()));
        jLabelcli.setText(String.valueOf(m.getNomeProduto()));
        jLabeltp.setText(String.valueOf(m.getValorVenda()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         m = ctl.Anterior();
       
        jLabelcv.setText(String.valueOf(m.getIdVenda()));
        jLabeldt.setText(String.valueOf(m.getIdProduto()));
        jLabelvl.setText(String.valueOf(m.getQtdItem()));
        jLabelcli.setText(String.valueOf(m.getNomeProduto()));
        jLabeltp.setText(String.valueOf(m.getValorVenda()));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed

        
        
        String[] options = {"Sim", "Não"};

        int resposta = JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir tudo , se tiver codigos na tabela ao lado iguais e preciso deleta-los antes ?",
                "Confirmar",JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        

        if (resposta == 1) {
        	
        	return;//Este é o Botao do NAO. Ira retornar para a Calculadora
        }else
                     
             
             
              if(resposta == 0){//Este é o Botao do SIM. Ira sair do seu Programa
                  preecherTabela2("delete  from itens_venda_produto");  
                    preecherTabela2("delete  from venda");  
                    
            }
        preecherTabela3("select sum(valor_venda)as valor_venda from venda");
                
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        dispose();
        new FrmTabelaDeVendasParceladas().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonPrimeiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiro1ActionPerformed
        // TODO add your handling code here:
        mv=ctlp.Primeiro();
        jLabelParcela.setText(String.valueOf(mv.getCodParcela()));
        jLabelCodVenda.setText(String.valueOf(mv.getCodV()));
        jLabelValorVenda.setText(String.valueOf(mv.getValorV()));
        jLabelValorTotal.setText(String.valueOf(mv.getValorT()));
        jLabelNumeroParcela.setText(String.valueOf(mv.getNumP()));
        jLabelValorParcela.setText(String.valueOf(mv.getValorP()));
        jLabelDataVencimento.setText(String.valueOf(mv.getData()));
        jLabelEstado.setText(String.valueOf(mv.getEstado()));
        
        
    }//GEN-LAST:event_jButtonPrimeiro1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        mv=ctlp.Anterior();
        jLabelParcela.setText(String.valueOf(mv.getCodParcela()));
        jLabelCodVenda.setText(String.valueOf(mv.getCodV()));
        jLabelValorVenda.setText(String.valueOf(mv.getValorV()));
        jLabelValorTotal.setText(String.valueOf(mv.getValorT()));
        jLabelNumeroParcela.setText(String.valueOf(mv.getNumP()));
        jLabelValorParcela.setText(String.valueOf(mv.getValorP()));
        jLabelDataVencimento.setText(String.valueOf(mv.getData()));
        jLabelEstado.setText(String.valueOf(mv.getEstado()));
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        mv=ctlp.Proximo();
        jLabelParcela.setText(String.valueOf(mv.getCodParcela()));
        jLabelCodVenda.setText(String.valueOf(mv.getCodV()));
        jLabelValorVenda.setText(String.valueOf(mv.getValorV()));
        jLabelValorTotal.setText(String.valueOf(mv.getValorT()));
        jLabelNumeroParcela.setText(String.valueOf(mv.getNumP()));
        jLabelValorParcela.setText(String.valueOf(mv.getValorP()));
        jLabelDataVencimento.setText(String.valueOf(mv.getData()));
        jLabelEstado.setText(String.valueOf(mv.getEstado()));
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonUltimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimo1ActionPerformed
        // TODO add your handling code here:
        mv=ctlp.Ultimo();
        jLabelParcela.setText(String.valueOf(mv.getCodParcela()));
        jLabelCodVenda.setText(String.valueOf(mv.getCodV()));
        jLabelValorVenda.setText(String.valueOf(mv.getValorV()));
        jLabelValorTotal.setText(String.valueOf(mv.getValorT()));
        jLabelNumeroParcela.setText(String.valueOf(mv.getNumP()));
        jLabelValorParcela.setText(String.valueOf(mv.getValorP()));
        jLabelDataVencimento.setText(String.valueOf(mv.getData()));
        jLabelEstado.setText(String.valueOf(mv.getEstado()));
        
    }//GEN-LAST:event_jButtonUltimo1ActionPerformed

    private void jButtonDeletar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletar1ActionPerformed
    
          if(jLabelParcela.getText().equals("")){
          JOptionPane.showMessageDialog(rootPane,"Informe um codigo  para exclui-lo!");
        }else{
            
            
        String[] options = {"Sim", "Não"};

        int resposta = JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir o codigo ?",
                "Confirmar",JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        

        if (resposta == 1) {
        	
        	return;//Este é o Botao do NAO. Ira retornar para a Calculadora
        }
        
        
       
        
        if(resposta == 0){//Este é o Botao do SIM. Ira sair do seu Programa
             preecherTabela("delete  from  parcela_venda  where id_parc_venda='"+jLabelParcela.getText()+"'");
              preecherTabela("select * from  parcela_venda ");
            }
        JOptionPane.showMessageDialog(rootPane, "Exclusão com sucesso");
        
              }

       
       
       
       
    
    }//GEN-LAST:event_jButtonDeletar1ActionPerformed

    private void jButtonPesquisarCodVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCodVActionPerformed
        // TODO add your handling code here:
        preecherTabela("select * from parcela_venda where cod_venda = '"+jTextFieldPesqCodV.getText()+"'");
       jTextFieldPesqCodV.setText("");
   
    }//GEN-LAST:event_jButtonPesquisarCodVActionPerformed

    private void jButtonCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCodActionPerformed
        // TODO add your handling code here:
        preecherTabela2("select * from itens_venda_produto where id_venda ='"+jTextFieldCod.getText()+"'");
        jTextFieldCod.setText("");
    }//GEN-LAST:event_jButtonCodActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String[] options = {"Sim", "Não"};

        int resposta = JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir o tudo ?",
                "Confirmar",JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        

        if (resposta == 1) {
        	
        	return;//Este é o Botao do NAO. Ira retornar para a Calculadora
        }else if(resposta == 0){//Este é o Botao do SIM. Ira sair do seu Programa
             preecherTabela("delete  from parcela_venda");
             preecherTabela("select * from parcela_venda");
            }
        JOptionPane.showMessageDialog(rootPane, "Exclusão com sucesso");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonDeletar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletar2ActionPerformed
        // TODO add your handling code here:
        
        String[] options = {"Sim", "Não"};

        int resposta = JOptionPane.showOptionDialog(null, "Tem certeza que deseja excluir tudo , se tiver codigos na tabela ao lado iguais e preciso deleta-los antes ?",
                "Confirmar",JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        

        if (resposta == 1) {
        	
        	return;//Este é o Botao do NAO. Ira retornar para a Calculadora
        }else
                     
             
             
              if(resposta == 0){//Este é o Botao do SIM. Ira sair do seu Programa
                  preecherTabela2("delete  from itens_venda_produto where id_venda='"+jLabelcv.getText()+"'");  
                    preecherTabela2("delete  from venda where id_venda='"+jLabelcv.getText()+"'");  
                    
            }
         preecherTabela2("select * from itens_venda_produto");
        preecherTabela3("select sum(valor_venda)as valor_venda from venda");
        
    }//GEN-LAST:event_jButtonDeletar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
     public void preecherTabela(String SQL){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"C.P","C.V","Valor.Venda","Valor.Total","N.P","Valor.Parcela","Data.Vencimento","Estado"};
     
      conn.execultasql(SQL);
        try {
            conn.rs.first();
            do{
                dados.add(new Object[]{conn.rs.getInt("id_parc_venda"),conn.rs.getString("cod_venda"),conn.rs.getString("valor_venda"),conn.rs.getString("valor_total"),conn.rs.getString("numero_parcela"),conn.rs.getString("valor_parce"),conn.rs.getString("datavenc"),conn.rs.getString("estado")});
      
       }while(conn.rs.next());  
        } catch (SQLException ex) {
            // JOptionPane.showMessageDialog(rootPane,"Tabela vazia" );
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
            jTable1.setModel(modelo);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(105);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getTableHeader().setReorderingAllowed(false);
            jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
            jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                         
          

}     
     
     
      public void preecherTabela2(String SQL){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"CodVend","CodProd","QuatVd","Produto","Valor"};
     
      conn.execultasql(SQL);
        try {
            conn.rs.first();
            do{
                dados.add(new Object[]{conn.rs.getInt("id_venda"),conn.rs.getInt("id_produto"),conn.rs.getInt("quantidade_produto"),conn.rs.getString("nome_produto"),conn.rs.getFloat("valor_venda")});
      
       }while(conn.rs.next());  
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"Tabela vazia" );
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
            jTable2.setModel(modelo);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(70);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(90);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            
            
            jTable2.getTableHeader().setReorderingAllowed(false);
            jTable2.setAutoResizeMode(jTable2.AUTO_RESIZE_OFF);
            jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                         
          
      }
      
      ////////////////
      
       public void preecherTabela3(String SQL){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Total"};
     
      conn.execultasql(SQL);
        try {
            conn.rs.first();
            do{
                dados.add(new Object[]{conn.rs.getFloat("valor_venda")});
      
       }while(conn.rs.next());  
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"Tabela vazia" );
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
            jTable3.setModel(modelo);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(60);
            
            
            
            jTable2.getTableHeader().setReorderingAllowed(false);
            jTable2.setAutoResizeMode(jTable3.AUTO_RESIZE_OFF);
            jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                         
          
      }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTabelaDeVendasParceladas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTabelaDeVendasParceladas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTabelaDeVendasParceladas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTabelaDeVendasParceladas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTabelaDeVendasParceladas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonCod;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonDeletar1;
    private javax.swing.JButton jButtonDeletar2;
    private javax.swing.JButton jButtonPesquisarCodV;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonPrimeiro1;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JButton jButtonUltimo1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel2Valor;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCodVenda;
    private javax.swing.JLabel jLabelDataVencimento;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNumeroParcela;
    private javax.swing.JLabel jLabelParcela;
    private javax.swing.JLabel jLabelValorParcela;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JLabel jLabelValorVenda;
    private javax.swing.JLabel jLabelcli;
    private javax.swing.JLabel jLabelcv;
    private javax.swing.JLabel jLabeldt;
    private javax.swing.JLabel jLabeltp;
    private javax.swing.JLabel jLabelvl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldPesqCodV;
    // End of variables declaration//GEN-END:variables
}
