/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visão;

import Controle.ConectaBanco;
import Modelo.ModeloTabela;
import Modelo.ModeloCliente;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import org.apache.xmlbeans.impl.schema.SchemaTypeSystemImpl;

/**
 *
 * @author Eduardo
 */
public class FrmVendaPesquisa extends javax.swing.JFrame {
    DecimalFormat formato;
    int cod;
    ConectaBanco conn = new ConectaBanco();
    ModeloCliente mod = new ModeloCliente();
    
     
    /**
     * Creates new form FrmVendaPesquisa
     */
    public FrmVendaPesquisa() {
        initComponents();
        
        
        formato = new DecimalFormat("#0.00");
        conn.conexao();
       
       // preecherTabela1("select * from venda inner join clientes on venda.id_cliente=clientes.id_cliente");
       // preecherTabela1("select * from venda inner join parcela_venda on venda.id_venda=parcela_venda.cod_venda inner join clientes on venda.id_cliente=clientes.id_cliente ");
        preecherTabela1("select * from venda inner join clientes on venda.id_cliente=clientes.id_cliente inner join parcela_venda on venda.id_venda=parcela_venda.cod_venda");
          try {
            MaskFormatter form = new MaskFormatter("##/##/####");
            jFormattedTextFieldPesquisar.setFormatterFactory(new DefaultFormatterFactory(form));
           
        } catch (ParseException ex) {
            Logger.getLogger(FrmCliente.class.getName()).log(Level.SEVERE, null, ex);    
       }
          
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablevenda = new javax.swing.JTable();
        jFormattedTextFieldPesquisar = new javax.swing.JFormattedTextField();
        jButtonBuscarCodigoPeloNomeCli = new javax.swing.JButton();
        jTextFieldCodigoCli = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jTextField1CodigoVenda = new javax.swing.JTextField();
        jTextFieldCodiCliTab = new javax.swing.JTextField();
        jButtonCodigo = new javax.swing.JButton();
        jButtonCodigo1 = new javax.swing.JButton();
        jTextFieldCodiCliTab2 = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel10 = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelPreV = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelCli = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCodigoCli = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelCodigoParcela = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabelDataVencimento = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelNP = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de venda");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Digite uma Data:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Vendas Realizadas ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("Detalhes da venda");

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        Tablevenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tablevenda);

        jFormattedTextFieldPesquisar.setForeground(new java.awt.Color(255, 153, 0));
        jFormattedTextFieldPesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jFormattedTextFieldPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextFieldPesquisarMouseClicked(evt);
            }
        });
        jFormattedTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldPesquisarActionPerformed(evt);
            }
        });

        jButtonBuscarCodigoPeloNomeCli.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jButtonBuscarCodigoPeloNomeCli.setText("Buscar o nome do cliente ");
        jButtonBuscarCodigoPeloNomeCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarCodigoPeloNomeCliActionPerformed(evt);
            }
        });

        jTextFieldCodigoCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCodigoCli.setForeground(new java.awt.Color(51, 102, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jButton2.setText("Pesquisar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1CodigoVenda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1CodigoVenda.setForeground(new java.awt.Color(255, 153, 51));

        jTextFieldCodiCliTab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCodiCliTab.setForeground(new java.awt.Color(255, 51, 0));

        jButtonCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCodigo.setText("Codigo do cliente");
        jButtonCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCodigoActionPerformed(evt);
            }
        });

        jButtonCodigo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCodigo1.setText("Codigo da venda");
        jButtonCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCodigo1ActionPerformed(evt);
            }
        });

        jTextFieldCodiCliTab2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldCodiCliTab2.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1CodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCodiCliTab, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCodigo)
                        .addGap(15, 15, 15)
                        .addComponent(jTextFieldCodiCliTab2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCodigo1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldCodigoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscarCodigoPeloNomeCli)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarCodigoPeloNomeCli))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButton2)
                    .addComponent(jTextField1CodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodiCliTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCodigo)
                    .addComponent(jButtonCodigo1)
                    .addComponent(jTextFieldCodiCliTab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 51));
        jDesktopPane1.setForeground(new java.awt.Color(0, 0, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Codigo da venda :");

        jLabelCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(0, 255, 0));
        jLabelCodigo.setText("Codigo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Preço de venda: ");

        jLabelPreV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPreV.setForeground(new java.awt.Color(51, 255, 0));
        jLabelPreV.setText("Preço");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("R$");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pagamento :");

        jLabelTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(0, 255, 0));
        jLabelTipo.setText("Tipo");

        jLabelCli.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCli.setForeground(new java.awt.Color(0, 255, 0));
        jLabelCli.setText("Cliente");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Codigo do cliente :");

        jLabelCodigoCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodigoCli.setForeground(new java.awt.Color(0, 255, 0));
        jLabelCodigoCli.setText("Codigo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pesquisa de Venda");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cliente :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("Data da Venda:");

        jLabelData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(0, 255, 51));
        jLabelData.setText("....");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Codigo da Parcela :");

        jLabelCodigoParcela.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCodigoParcela.setForeground(new java.awt.Color(0, 255, 0));
        jLabelCodigoParcela.setText("Codigo");

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setText("Data de Vencimento:");

        jLabelDataVencimento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDataVencimento.setForeground(new java.awt.Color(0, 255, 51));
        jLabelDataVencimento.setText("....");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Parcela");

        jLabelNP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelNP.setForeground(new java.awt.Color(0, 255, 0));
        jLabelNP.setText("....");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13)
                        .addGap(32, 32, 32)
                        .addComponent(jLabelCli)
                        .addGap(117, 117, 117)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCodigoCli))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCodigoParcela))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(52, 52, 52)
                                .addComponent(jLabelData)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(35, 35, 35)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabelCodigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(64, 64, 64))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabelPreV)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel11)
                                        .addGap(47, 47, 47)
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabelDataVencimento))
                                        .addGap(30, 30, 30)))
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNP)))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(215, 215, 215))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(161, 161, 161))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabelCli, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabelPreV)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabelTipo)
                            .addComponent(jLabel6)
                            .addComponent(jLabelCodigoCli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabelCodigo)
                                .addComponent(jLabelNP)
                                .addComponent(jLabel9))
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(jLabelCodigoParcela)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabelData)
                    .addComponent(jLabel16)
                    .addComponent(jLabelDataVencimento)
                    .addComponent(jButton3))
                .addContainerGap())
        );
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelPreV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelCli, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelCodigoCli, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelCodigoParcela, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelDataVencimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelNP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldPesquisarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
       
            // TODO add your handling code here:
            
            preencherTabela("select * from venda inner join clientes on venda.id_cliente=clientes.id_cliente where data_venda='"+jFormattedTextFieldPesquisar.getText()+"'");
            
            jFormattedTextFieldPesquisar.setText("");
                
          
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jFormattedTextFieldPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPesquisarMouseClicked
        // TODO add your handling code here:
       // preencherTabela("select * from venda inner join clientes on venda.id_cliente=clientes.id_cliente where data_venda="+cod);
    }//GEN-LAST:event_jFormattedTextFieldPesquisarMouseClicked

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        Object cod = Table.getValueAt(Table.getSelectedRow(), 0);
        preencherTabelaDetalhesdaVenda("select * from   venda inner join itens_venda_produto on venda.id_venda=itens_venda_produto.id_venda inner join produto on itens_venda_produto.id_produto = produto.id_produto where venda.id_venda="+cod);
    }//GEN-LAST:event_TableMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        
            String codigop = ""+jTable1.getValueAt(jTable1.getSelectedRow(),0);
            jLabelCodigoParcela.setText(codigop);
            
            
            String codigov = ""+jTable1.getValueAt(jTable1.getSelectedRow(),1);
            jLabelCodigo.setText(codigov);
            jTextField1CodigoVenda.setText(codigov);
            
            String data = ""+jTable1.getValueAt(jTable1.getSelectedRow(),2);// pega a data para inserir
            jLabelData.setText(data);
            jFormattedTextFieldPesquisar.setText(data);
            
            String datav = ""+jTable1.getValueAt(jTable1.getSelectedRow(),3);// pega a data para inserir
            jLabelDataVencimento.setText(datav);
            //jFormattedTextFieldPesquisar.setText(datav);
            
            String np = ""+jTable1.getValueAt(jTable1.getSelectedRow(),4);
            jLabelNP.setText(np);
            
            String pre = ""+jTable1.getValueAt(jTable1.getSelectedRow(),5);// pega o codigo para inserir
            // conversao para float
            jLabelPreV.setText( formato.format(Float.parseFloat(pre))); // inseri
            
            
            
            String clie = ""+jTable1.getValueAt(jTable1.getSelectedRow(),6);// pega o codigo
            
            jLabelCodigoCli.setText(clie);
            
            String clien = ""+jTable1.getValueAt(jTable1.getSelectedRow(),7);// pega o codigo
            
            jLabelCli.setText( clien);
            
            
            
            String tipo = ""+jTable1.getValueAt(jTable1.getSelectedRow(),8);// pega o codigo
            
            jLabelTipo.setText(tipo);
       
         
       
        
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonBuscarCodigoPeloNomeCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarCodigoPeloNomeCliActionPerformed
        // TODO add your handling code here:
        
        try {
            conn.conexao();
            conn.execultasql("select  * from clientes where nome_cliente like '%"+jTextFieldCodigoCli.getText()+"%'");         
            conn.rs.first();
            
            jLabelCodigoCli.setText(conn.rs.getString("id_cliente"));
            jLabelCli.setText(conn.rs.getString("nome_cliente"));
            jTextFieldCodiCliTab.setText(conn.rs.getString("id_cliente"));
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao buscar o nome  do cliente");
        }
        
        
        jTextFieldCodigoCli.setText("");
    }//GEN-LAST:event_jButtonBuscarCodigoPeloNomeCliActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
           preencherTabela("select * from venda inner join clientes on venda.id_cliente=clientes.id_cliente where id_venda='"+jTextField1CodigoVenda.getText()+"'");
      // preencherTabela("select * from venda  where id_venda='"+jTextField1CodigoVenda.getText()+"'");
        jTextField1CodigoVenda.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCodigoActionPerformed
        // TODO add your handling code here:
        
       
         
        preecherTabela1("select * from venda inner join clientes on venda.id_cliente=clientes.id_cliente inner join parcela_venda on venda.id_venda=parcela_venda.cod_venda where venda.id_cliente = '"+jTextFieldCodiCliTab.getText()+"'");
        
       
        
        
        
    }//GEN-LAST:event_jButtonCodigoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new FrmVendaPesquisa().setVisible(true);
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCodigo1ActionPerformed
        // TODO add your handling code here:
         preecherTabela1("select * from venda inner join clientes on venda.id_cliente=clientes.id_cliente inner join parcela_venda on venda.id_venda=parcela_venda.cod_venda where venda.id_venda = '"+jTextFieldCodiCliTab2.getText()+"'"); 
    }//GEN-LAST:event_jButtonCodigo1ActionPerformed
    public void preencherTabela(String sql){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"ID","Data Venda","P.V ","Cliente"};
        conn.conexao();
        conn.execultasql(sql);                
            try {
                conn.rs.first();
                do {
                    //JOptionPane.showMessageDialog(rootPane,conn.rs.getInt(1));
                    dados.add(new Object[]{conn.rs.getInt("id_venda"),conn.rs.getString("data_venda"),conn.rs.getString("valor_venda"),conn.rs.getString("nome_cliente")});
                }while(conn.rs.next());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane,"Erro ao preencher o ArrayList!\nErro:"+ex);
            }
          ModeloTabela modelo = new ModeloTabela(dados, Colunas);
          Table.setModel(modelo);
          Table.getColumnModel().getColumn(0).setPreferredWidth(50);
          Table.getColumnModel().getColumn(0).setResizable(false);
          Table.getColumnModel().getColumn(1).setPreferredWidth(100);
          Table.getColumnModel().getColumn(1).setResizable(false); 
          Table.getColumnModel().getColumn(2).setPreferredWidth(50);
          Table.getColumnModel().getColumn(2).setResizable(false);
          Table.getColumnModel().getColumn(3).setPreferredWidth(150);
          Table.getColumnModel().getColumn(3).setResizable(false); 
          Table.getTableHeader().setReorderingAllowed(false);
          Table.setAutoResizeMode(Table.AUTO_RESIZE_OFF);
          Table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                   
    }
    public void preencherTabelaDetalhesdaVenda(String sql){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"Produtos","Quantidade"};
        conn.conexao();
        conn.execultasql(sql);                
            try {
                conn.rs.first();
                do {
                    //JOptionPane.showMessageDialog(rootPane,conn.rs.getInt(1));
                    dados.add(new Object[]{conn.rs.getString("nome_produto"),conn.rs.getString("quantidade_produto")});
                }while(conn.rs.next());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane,"Erro ao preencher o ArrayList!\nErro:"+ex);
            }
          ModeloTabela modelo = new ModeloTabela(dados, Colunas);
          Tablevenda.setModel(modelo);
          Tablevenda.getColumnModel().getColumn(0).setPreferredWidth(200);
          Tablevenda.getColumnModel().getColumn(0).setResizable(false);
          Tablevenda.getColumnModel().getColumn(1).setPreferredWidth(90);
          Tablevenda.getColumnModel().getColumn(1).setResizable(false);              
          Tablevenda.getTableHeader().setReorderingAllowed(false);
          Tablevenda.setAutoResizeMode(Tablevenda.AUTO_RESIZE_OFF);
          Tablevenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                   
    }
    
    
      public void preecherTabela1(String SQL){
        ArrayList dados = new ArrayList();
        String[] Colunas = new String[]{"C.P","C.V","Data.Venda","Dat.ven","N.P","Valor.V","C.cli","Nome","Tipo Pag"};
     
      conn.execultasql(SQL);
        try {
            conn.rs.first();
            do{
                dados.add(new Object[]{conn.rs.getInt("id_parc_venda"),conn.rs.getInt("id_venda"),conn.rs.getString("data_venda"),conn.rs.getString("datavenc"),conn.rs.getInt("numero_parcela"),conn.rs.getString("valor_venda"),conn.rs.getInt("id_cliente"),conn.rs.getString("nome_cliente"),conn.rs.getString("tipo_pagamento")});
         
          
       }while(conn.rs.next());  
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane,"Não tem venda para este cliente !" );
        }
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
            jTable1.setModel(modelo);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            
            
            
            
            jTable1.getTableHeader().setReorderingAllowed(false);
            jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
            jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);                                         
          

}  
     
     
      
      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVendaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVendaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVendaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVendaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVendaPesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JTable Tablevenda;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBuscarCodigoPeloNomeCli;
    private javax.swing.JButton jButtonCodigo;
    private javax.swing.JButton jButtonCodigo1;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFormattedTextField jFormattedTextFieldPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCli;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigoCli;
    private javax.swing.JLabel jLabelCodigoParcela;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelDataVencimento;
    private javax.swing.JLabel jLabelNP;
    private javax.swing.JLabel jLabelPreV;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1CodigoVenda;
    private javax.swing.JTextField jTextFieldCodiCliTab;
    private javax.swing.JTextField jTextFieldCodiCliTab2;
    private javax.swing.JTextField jTextFieldCodigoCli;
    // End of variables declaration//GEN-END:variables
}
